### ISSUE TITLE
Error while using the code

### ISSUE THREAD

**Issue by raviteja6760** [Jakobimatrix/multi-language-website-JS#1]
Hello,

When I was trying to use this code an exception was thrown. Could you please let me know what exactly the problem was. Please find the attached screenshot below for your reference.

![image](https://user-images.githubusercontent.com/31928005/104130419-f06c3d00-5370-11eb-87a4-fa49b0b3709c.png)

![image](https://user-images.githubusercontent.com/31928005/104130442-0843c100-5371-11eb-9557-8936dfa14e85.png)

**Comment by Jakobimatrix** [comment]
Sorry for answering so late. I did not get notified (or I missed the mail). It might be a bit late for you, but I fixed the problem: The DOM element was never a child of the document.body, but of the div I added it to...
