### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by ghost** [Jakobimatrix/multi-language-website-JS#2]
I want to be as niceas possible but in README.md and the repo discription you have misspelled the word "using". Just a nice little reminder.

Regards
Maciej Czerwonka

**Comment by Jakobimatrix** [comment]
Hi Maciej Czerwonka,

very nice of you to point out that issue.

This commit should fix the issue: 
https://github.com/Jakobimatrix/multi-language-website-JS/commit/83ee0f1d0d8a61ae636f35d2a563928ecdc1f4f0
Hence I am closing this issue.

Best Regards
Jakob Wandel
